version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-node-browsers'
    working_directory: ~/pet_book
    steps:
      - checkout
      - run: 
          name: Install CLI
          command: npm install @angular/cli
      - run:
          name: Install dependencies and build project
          command: npm install 
      - run:
          name: Build Project
          command: npm run-script build
      - run:
          name: Run unit test
          no_output_timeout: 30m
          command: npm run test-ci
      - sonarcloud/scan
      - aws-s3/sync:     
          arguments: |
            --acl public-read
          overwrite: true
          from: ~/pet_book/dist/pet-book
          to: 's3://pet-book-project-circleci'
      - checkout
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      # build the application image
      - run: docker build -t danielmunozo/pet-book-ci:dockerfile .

      # deploy the image
      - run: docker push danielmunozo/pet-book-ci:dockerfile
  test:
     docker:
       - image: 'circleci/openjdk:8-node-browsers'
     steps:
       - run:
           name: Clone repository
           command: git clone https://github.com/Danielm1229/automatization-petbook
       - run:
           name: Move to serenity and test
           command: cd automatization-petbook && ./gradlew test
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  aws-s3: circleci/aws-s3@1.0.15
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - test: 
          requires:
            - build
